name: CI Checking

on: [pull_request]

jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: build/ubuntu-22.04
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libvirt-dev python3-bpfcc aspell
          pip3 install --upgrade pip
          pip3 install pylint
          pip3 install -r utils/pycloudstack/requirements.txt
          pip3 install -r attestation/pytdxmeasure/requirements.txt
          pip3 install -r tests/requirements.txt
      - name: Analysing the code with pylint
        run: |
          set -ex
          export PYTHONPATH=$PWD/utils/pycloudstack:$PWD/attestation/pytdxmeasure:/lib/python3/dist-packages/
          find . -path ./build -prune -o -name *.py -print0 | xargs -n 1 -0 python3 -m pylint
      - name: Spell Check
        run: |
          for f in $(find -type f -name "*.md"); do
            OUTPUT=$(cat $f | aspell -l en --mode markdown --personal $PWD/.github/workflows/.aspell.en.pws list)
            if [[ ! -z $OUTPUT ]]; then
              echo "Misspelled words in $f:"
              echo $OUTPUT
              ret=1
            fi
          done
          exit $ret
