name: PR General Checking

on: [pull_request]

jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Exclude ubuntu-22.04
        run: |
          rm -rf build/ubuntu-22.04
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: "build/centos-stream-8/pkg-builder/Dockerfile"
          lint: "hadolint"
      - uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: "build/centos-stream-8/pkg-builder/Dockerfile"
          lint: "dockerlint"
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install libvirt-dev
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r utils/pycloudstack/requirements.txt
          pip install -r utils/pytdxmeasure/requirements.txt
          pip install -r tests/requirements.txt
      - name: Analysing the code with pylint
        run: |
          set -ex
          export PYTHONPATH=utils/pycloudstack:utils/pytdxmeasure
          find . -name *.py -print0 | xargs -n 1 -0 pylint
