name: Build PCCS Container

on:
  pull_request:
    paths:
    - 'attestation/pccs-k8s/container/**'
  workflow_dispatch:

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: attestation/pccs-k8s/container/Dockerfile
          push: false
