name: Validate PR for RHEL8 ovmf

on:
  pull_request:
    paths:
    - 'build/rhel-8/intel-mvp-ovmf/**'
  workflow_dispatch:

jobs:
  build_package:
    name: Build ovmf for RHEL8
    runs-on: [self-hosted,rhel]
    steps:
      - name: Cleanup workspace for the job (self hosted only)
        run: |
          sudo rm -fr *
      - id: checkout_self
        name: Check out PR
        uses: actions/checkout@v3
      - id: build
        name: Build the source and binary packages
        run: |
          cd build/rhel-8/intel-mvp-ovmf/
          ./build.sh
