name: Validate PR for Ubuntu-22.04 build-repo.sh

on:
  workflow_dispatch:

jobs:
  build_package:
    name: Build TDX Stack for Ubuntu 22.04
    runs-on: self-hosted
    steps:
      - id: cleanup_workspace
        name: Cleanup workspace for the job (self hosted only)
        run: |
          sudo rm -fr * .* || true
      - id: checkout_self
        name: Check out PR
        uses: actions/checkout@v3
      - id: build_ubuntu
        name: Build the source and binary packages
        run: |
          cd build/ubuntu-22.04/
          ./pkg-builder build-repo.sh
