name: Publish pytdxmeasure package to PyPI

on:
  workflow_dispatch:


jobs:
  publish_pypi:
    name: Publish pytdxmeasure package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout action repository
        uses: actions/checkout@v3

      - name: Publish package
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m pip install --upgrade twine build wheel
          cd attestation/pytdxmeasure
          python3 setup.py bdist_wheel
          python3 -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --repository pypi dist/*
