# Default values for tdx-qgs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dongx1x/tdx-qgs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.15.100.3-jammy1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  sgx.intel.com/quote-provider: "tdx-qgs"

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    sgx.intel.com/epc: "128Mi"

nodeSelector:
  feature.node.kubernetes.io/cpu-security.tdx.enabled: "true"

tolerations: []

affinity: {}
