apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dcap-pccs.fullname" . }}-config
data:
  default.json: |-
    {
        "HTTPS_PORT" : 8081,
        "hosts" : "0.0.0.0",
        "uri": "{{ .Values.PCCSConfig.uri }}",
        "ApiKey": "{{ .Values.PCCSConfig.apiKey }}",
        "proxy" : "{{ .Values.PCCSConfig.proxy }}",
        "RefreshSchedule": "0 0 1 * * *",
        "UserTokenHash" : "{{ .Values.PCCSConfig.userToken }}",
        "AdminTokenHash" : "{{ .Values.PCCSConfig.adminToken }}",
        "CachingFillMode" : "LAZY",
        "LogLevel" : "debug",
        "DB_CONFIG" : "sqlite",
        "sqlite" : {
            "database" : "database",
            "username" : "username",
            "password" : "password",
            "options" : {
                "host": "localhost",
                "dialect": "sqlite",
                "pool": {
                    "max": 5,
                    "min": 0,
                    "acquire": 30000,
                    "idle": 10000
                },
                "define": {
                    "freezeTableName": true
                },
                "logging" : false,
                "storage": "/data/pckcache.db"
            }
        },
        "mysql" : {
            "database" : "pckcache",
            "username" : "root",
            "password" : "mypass",
            "options" : {
                "host": "localhost",
                "dialect": "mysql",
                "pool": {
                    "max": 5,
                    "min": 0,
                    "acquire": 30000,
                    "idle": 10000
                },
                "define": {
                    "freezeTableName": true
                },
                "logging" : false
            }
        }
    }

