apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcap-pccs.fullname" . }}
  labels:
    {{- include "dcap-pccs.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dcap-pccs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dcap-pccs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "dcap-pccs.fullname" . }}-config
              mountPath: /opt/intel/sgx-dcap-pccs/config
            - name: {{ include "dcap-pccs.fullname" . }}-data
              mountPath: /data/
            - name: {{ .Values.PCCSConfig.sslSecret }}
              mountPath: /opt/intel/sgx-dcap-pccs/ssl_key/
              readOnly: true
      volumes:
        - name: {{ include "dcap-pccs.fullname" . }}-config
          configMap:
            name: {{ include "dcap-pccs.fullname" . }}-config
        - name: {{ include "dcap-pccs.fullname" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "dcap-pccs.fullname" . }}-data
        - name: {{ .Values.PCCSConfig.sslSecret }}
          secret:
            secretName: {{ .Values.PCCSConfig.sslSecret }}   
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
