apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dcap-pccs.fullname" . }}-data
  labels:
    {{- include "dcap-pccs.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
